[package]
name = "brasa-daemon"
description = "API HTTP local, scheduler y Model Manager."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
brasa-core.workspace = true
brasa-runtime.workspace = true
brasa-catalog.workspace = true

[lints]
workspace = true
